#!/bin/bash
#This script is only used if you did a manual installation of CosmoSIS;
#i.e. if you did not use the "bootstrap" script and have no "ups" directory

#See the wiki https://bitbucket.org/joezuntz/cosmosis/wiki/Manual%20Install
#on how to change and use this file


export COSMOSIS_SRC_DIR=/home/cosmos/cosmosis

#The gnu science library
export GSL_INC=/usr/include/gsl
export GSL_LIB=/usr/lib/x86_64-linux-gnu

#The cfitsio FITS library
export CFITSIO_INC=/opt/cfitsio/include
export CFITSIO_LIB=/opt/cfitsio/lib

#The fftw3 Fourier transform library
export FFTW_LIBRARY=/usr/lib/x86_64-linux-gnu
export FFTW_INCLUDE_DIR=/usr/include

#The lapack linear algebra package
#On a mac this should just say "-framework Accelerate" or "-framework veclib" if that doesn't work
export LAPACK_LINK="-lopenblas"


#You may need to add :${DYLD_LIBRARY_PATH} to the end of this
export DYLD_LIBRARY_PATH=/usr/bin/gfortran:${COSMOSIS_SRC_DIR}/cosmosis/datablock/:${COSMOSIS_SRC_DIR}/cosmosis-standard-library/likelihood/:${COSMOSIS_SRC_DIR}/cosmosis-standard-library/likelihood/planck/plc-1.0/lib/:${COSMOSIS_SRC_DIR}/cosmosis-standard-library/likelihood/planck2015/plc-2.0/lib/:${DYLD_LIBRARY_PATH}

#You may need to add :${LD_LIBRARY_PATH} to the end of this
export LD_LIBRARY_PATH=/usr/bin/gfortran:${COSMOSIS_SRC_DIR}/cosmosis/datablock/:${COSMOSIS_SRC_DIR}/cosmosis-standard-library/likelihood/planck/plc-1.0/lib/:${COSMOSIS_SRC_DIR}/cosmosis-standard-library/likelihood/planck2015/plc-2.0/lib/:${LD_LIBRARY_PATH}


export PYTHONPATH=${COSMOSIS_SRC_DIR}:${PYTHONPATH}
export PATH=${COSMOSIS_SRC_DIR}/bin:/usr/bin/:/opt/conda/bin/python/:${PATH}
